# Please fill in each of the below with the correct values for your env
# and rename to constants.py.
# DO NOT COMMIT TO GIT OR EXPOSE PUBLICLY!! CONTAINS API KEY/SECRETS
ELASTICSEARCH_HOST = ''
ELASTICSEARCH_PORT = ''
PASTEBIN_API_KEY = ''
PASTEBIN_USER = ''
PASTEBIN_PASS = ''
TWITTER_API_KEY = ''
TWITTER_SECRET = ''
TWITTER_ACCESS_TOKEN = ''
TWITTER_ACCESS_SECRET = ''